"""First migration

Revision ID: 12398f1000ca
Revises: 
Create Date: 2021-02-23 20:52:58.324557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12398f1000ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
