"""Latest database upgrade

Revision ID: 383bbfc27780
Revises: 12398f1000ca
Create Date: 2021-10-16 02:34:42.380394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383bbfc27780'
down_revision = '12398f1000ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
